os: osx
osx_image: xcode9.1
language: node_js
node_js: node
cache:
  directories:
  - node_modules
script:
- npm test
env:
  global:
    secure: Fi7IsiQ9aVPFCB22rBx1gAmO1rEZ4S2zHQ9ouYjTcHhoks1vZN+6ZV557X95KpQ99ww792/r2jvXbTP9OyrGQQolY0O1OdvUSMdlGIrk/5SXjGCnxMi9g5jrq+qLuaIMXo+VqJ9J5ZkuJOgIaLzBcWi/fhNae4itYWV84SrMPMpdxjia5fCxoa80YdRgw5se5lUeQggW81RPpfdIPwHayBj3+YvYPa/g2lzETzDdIyHsTz9a5iGLaHjQgUK9ceUq8LJJFHw3mBX7U3yVTDaWrVgqYLp9tiwtMs+5Km+IrPuV4A5a7mlivgqAwF9W5La7zphvQmHD+1JYSgjx0mjhF5qQ3gisE7vzywaD8LqjODRUUeUiiTqTaWaPfJZssqAbkDkMV/6Uv/pzH09f/jIwACcKjtQsRb+9trkPlvJd8ssSlXiAtzlJLKv4u9JZ3xgJvr0viqJ7/3vmD01LNy/A0T0pTwBfigVGU6xZOwPlcAPopbNMbMw66KBF1qJAVMy/JtdhKLHkH+ayopnMwo4O5N9MwdcV84xjJsHWXtc12P9Jw2HyTHrr3s2o7IFiCqYuAt2BGiy/XH5z08L/2ZYqGzD6IPZwZahuCW2GtquSaPgkmuOM6vv+E7nIfLDYMB+/WHuNIUEh1xiDM4l2T00dwOjRSPEqgkxHQbSSM/wK4IQ=
